clone_depth: 10

cache:
 - cmake-inst

environment:
  matrix:
    - GENERATOR: "NMake Makefiles"
      VS_VERSION: "12.0"
    - GENERATOR: "Visual Studio 10 2010"
      VS_VERSION: "10.0"
    - GENERATOR: "Visual Studio 11 2012"
      VS_VERSION: "11.0"
    - GENERATOR: "Visual Studio 12 2013"
      VS_VERSION: "12.0"
    - GENERATOR: "Visual Studio 14"
      VS_VERSION: "14.0"

matrix:
  fast_finish: true

before_build:
 - git submodule update --init --recursive

install:
 - ps: cmake -P .cmake-download-script
 - ps: gem install coveralls-lcov

build_script:
 - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
 - cmd: call "C:/Program Files (x86)/Microsoft Visual Studio %VS_VERSION%/Common7/Tools/vsvars32.bat"
 - cmd: cmake --version
 - cmd: cd tests
 - cmd: mkdir build
 - cmd: cd build
 - cmd: cmake .. -Wdev --warn-uninitialized -G"%GENERATOR%" -DCMAKE_UNIT_LOG_COVERAGE=1
 - cmd: cmake --build .

test_script:
 - cmd: ctest -C Debug --output-on-failure
 - cmd: cd ../../

on_success:
 - ps: cmake -DTRACEFILE="tests/build/CMakeUnitTests.trace" -DLCOV_OUTPUT="tests/build/coverage.info" -P CMakeTraceToLCov.cmake
# Don't submit coverage report for now, it appears that coveralls-lcov is broken on AppVeyor
# (certificate verification error)
# - ps: coveralls-lcov tests/build/coverage.info